apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: restapp      
  template: 
    metadata:
      labels:
        app.kubernetes.io/name: restapp
    spec:
      containers:
        - name: restapi
          image: docker.io/akashash/evaluation-task_restapi:latest
          env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
          ports:
          - containerPort: 8000     
